extends Node2D
class_name MushroomGlow

@onready var inner_glow : PointLight2D = $InnerGlow
@onready var outer_glow : PointLight2D = $OuterGlow
@onready var animation : AnimationPlayer = $GlowAnimation

@export var colour_name : String = "blue"

func _ready() -> void:
	Log.pr("And dog said let their be light...")
	Log.pr(position, global_position)
	set_light_colour(colour_name)
	animation.play("GlowFlicker")


func set_light_colour(colour : String) -> void:
	if colour == "blue":
		inner_glow.color = "4cc5fa"
		outer_glow.color = "00b4ff"
	elif colour == "yellow":
		inner_glow.color = "ffcf3c"
		outer_glow.color = "ffcf3c"
